In [20]:
import pandas as pd
election = pd.read_csv('2016_election.csv')
div = pd.read_csv('diversityindex.csv')
edu = pd.read_excel('education_25_older.xls')
pop = pd.read_excel('us_county_populations.xls')
ue_rates = pd.read_excel('Unemployment Rates.xls')

In [23]:
election.head()

,Unnamed: 0,votes_dem,votes_gop,total_votes,per_dem,per_gop,diff,per_point_diff,state_abbr,county_name,combined_fips
0,0,93003.0,130413.0,246588.0,0.377159,0.52887,"37,410",15.17%,AK,Alaska,2013
1,1,93003.0,130413.0,246588.0,0.377159,0.52887,"37,410",15.17%,AK,Alaska,2016
2,2,93003.0,130413.0,246588.0,0.377159,0.52887,"37,410",15.17%,AK,Alaska,2020
3,3,93003.0,130413.0,246588.0,0.377159,0.52887,"37,410",15.17%,AK,Alaska,2050
4,4,93003.0,130413.0,246588.0,0.377159,0.52887,"37,410",15.17%,AK,Alaska,2060

In [12]:
div.head()

,Location,Diversity-Index,"Black or African American alone, percent, 2013","American Indian and Alaska Native alone, percent, 2013","Asian alone, percent, 2013","Native Hawaiian and Other Pacific Islander alone, percent,","Two or More Races, percent, 2013","Hispanic or Latino, percent, 2013","White alone, not Hispanic or Latino, percent, 2013"
0,"Aleutians West Census Area, AK",0.769346,7.4,13.8,31.1,2.3,4.8,14.6,29.2
1,"Queens County, NY",0.742224,20.9,1.3,25.2,0.2,2.7,28.0,26.7
2,"Maui County, HI",0.740757,0.8,0.6,28.8,10.6,23.3,10.7,31.5
3,"Alameda County, CA",0.740399,12.4,1.2,28.2,1.0,5.2,22.7,33.2
4,"Aleutians East Borough, AK",0.738867,7.7,21.8,41.4,0.7,3.7,13.5,12.9

In [14]:
pop.head()

,state,county,est_pop_2015,pop_change_2015,int_mig_2015,dom_mig_2015,mig_2015
0,AL,Alabama,4858979,12568,5726,-2268,3458
1,AL,Autauga County,55347,57,19,-140,-121
2,AL,Baldwin County,203709,3996,221,3469,3690
3,AL,Barbour County,26489,-326,0,-281,-281
4,AL,Bibb County,22583,34,21,4,25

In [21]:
ue_rates.head()

,State,county_state,labor_force_2015,employed_2015,unemployed_2015,unemployment_rate_2015,med_household_income_2015
0,AL,Alabama,2146157,2015189,130968,6.1,44833
1,AL,"Autauga County, AL",25308,23981,1327,5.2,56580
2,AL,"Baldwin County, AL",87316,82525,4791,5.5,52387
3,AL,"Barbour County, AL",8625,7854,771,8.9,31433
4,AL,"Bibb County, AL",8490,7929,561,6.6,40767

In [22]:
va_el = election[election['state_abbr']=='VA']
va_edu = edu[edu['State']=='VA']
va_pop = pop[pop['state']=='VA'] 
va_ue_rates =  ue_rates[ue_rates['State']=='VA']

In [ ]:
right = election.set_index(election.county_name)
left = div.set_index(div.county_name)
combined_1 = right.join(left, lsuffix = '', rsuffix = '_r')
combined_1 = comined_1.reset_index()